using Microsoft.CodeAnalysis;

namespace WorkflowLensClient.Generators
{
    /// <summary>
    /// Generatorがユーザープロジェクトに注入する属性のソーステキスト。
    /// </summary>
    internal static class AttributeSources
    {
        public const string WorkflowActionsAttributeName = "WorkflowLensClient.WorkflowActionsAttribute";
        public const string WorkflowLogAttributeName = "WorkflowLensClient.WorkflowLogAttribute";
        public const string WorkflowLensLoggerAttributeName = "WorkflowLensClient.WorkflowLensLoggerAttribute";

        public const string WorkflowActionsSource = @"// <auto-generated />
using System;

namespace WorkflowLensClient
{
    /// <summary>
    /// enumに付与すると、CategoryLoggerの拡張メソッドを自動生成する。
    /// enumの各メンバーがactionに対応する（PascalCase → snake_case変換）。
    /// </summary>
    [AttributeUsage(AttributeTargets.Enum)]
    public sealed class WorkflowActionsAttribute : Attribute
    {
        public Category Category { get; }
        public WorkflowActionsAttribute(Category category) => Category = category;
    }
}
";

        public const string WorkflowLogSource = @"// <auto-generated />
#nullable enable
using System;

namespace WorkflowLensClient
{
    /// <summary>
    /// privateメソッドに付与すると、MeasureScopeで囲むpublicラッパーメソッドを自動生成する。
    /// 含むクラスはpartialである必要がある。
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class WorkflowLogAttribute : Attribute
    {
        public Category Category { get; }
        public string Action { get; }

        /// <summary>生成されるpublicメソッドの名前（省略時はCoreサフィックスを除去）。</summary>
        public string? MethodName { get; set; }

        public WorkflowLogAttribute(Category category, string action)
        {
            Category = category;
            Action = action;
        }
    }
}
";

        public const string WorkflowLensLoggerSource = @"// <auto-generated />
using System;

namespace WorkflowLensClient
{
    /// <summary>
    /// フィールドに付与して、Source GeneratorにWorkflowLensインスタンスの場所を通知する。
    /// [WorkflowLog]と組み合わせて使用する。
    /// </summary>
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class WorkflowLensLoggerAttribute : Attribute { }
}
";
    }
}
