using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WorkflowLensClient.Generators
{
    /// <summary>
    /// [WorkflowActions(Category.Xxx)] が付いたenumから
    /// CategoryLoggerの拡張メソッドを自動生成するSource Generator。
    /// </summary>
    [Generator]
    public class CategoryApiGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new EnumSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // 属性が既にcompilationに存在しなければソースを注入
            var existingAttr = context.Compilation.GetTypeByMetadataName(AttributeSources.WorkflowActionsAttributeName);
            if (existingAttr == null)
            {
                context.AddSource("WorkflowActionsAttribute.g.cs",
                    SourceText.From(AttributeSources.WorkflowActionsSource, Encoding.UTF8));
            }

            if (context.SyntaxReceiver is not EnumSyntaxReceiver receiver)
                return;

            var compilation = context.Compilation;

            foreach (var enumDecl in receiver.CandidateEnums)
            {
                var model = compilation.GetSemanticModel(enumDecl.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(enumDecl) as INamedTypeSymbol;
                if (symbol == null) continue;

                // [WorkflowActions] 属性を探す（生成コード内の属性はシンボル解決できない場合があるため名前で照合）
                var attr = symbol.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name == "WorkflowActionsAttribute" ||
                    a.AttributeClass?.ToDisplayString() == AttributeSources.WorkflowActionsAttributeName);
                if (attr == null) continue;

                // Category引数を取得
                if (attr.ConstructorArguments.Length == 0) continue;
                var categoryValue = attr.ConstructorArguments[0].Value;
                if (categoryValue == null) continue;
                var categoryName = GetCategoryName((int)categoryValue);
                if (categoryName == null) continue;

                // enum が public でなければ診断
                if (symbol.DeclaredAccessibility != Accessibility.Public)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.WLSG0001_EnumMustBePublic,
                        enumDecl.Identifier.GetLocation(),
                        symbol.Name));
                    continue;
                }

                // enumメンバーから拡張メソッドを生成
                var members = symbol.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f => f.HasConstantValue)
                    .ToList();

                if (members.Count == 0) continue;

                var source = GenerateExtensionClass(categoryName, members);
                context.AddSource($"WorkflowLens{categoryName}Extensions.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GenerateExtensionClass(string categoryName, List<IFieldSymbol> members)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using WorkflowLensClient;");
            sb.AppendLine();
            sb.AppendLine($"namespace WorkflowLensClient");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{categoryName}カテゴリの型安全なログ送信メソッド。</summary>");
            sb.AppendLine($"    public static class WorkflowLens{categoryName}Extensions");
            sb.AppendLine("    {");

            foreach (var member in members)
            {
                var pascalName = member.Name;
                var snakeName = PascalToSnakeCase.Convert(pascalName);

                // Log メソッド
                sb.AppendLine($"        /// <summary>{categoryName}/{snakeName} ログを送信する。</summary>");
                sb.AppendLine($"        public static void {pascalName}(this CategoryLogger logger, long? durationMs = null)");
                sb.AppendLine($"            => logger.Log(\"{snakeName}\", durationMs);");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Category enumの値から名前を取得する。</summary>
        private static string? GetCategoryName(int value)
        {
            return value switch
            {
                0 => "Asset",
                1 => "Build",
                2 => "Edit",
                3 => "Error",
                4 => "Session",
                _ => null,
            };
        }

        /// <summary>[WorkflowActions]属性付きのenum候補を収集する。</summary>
        private class EnumSyntaxReceiver : ISyntaxReceiver
        {
            public List<EnumDeclarationSyntax> CandidateEnums { get; } = new List<EnumDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is EnumDeclarationSyntax enumDecl &&
                    enumDecl.AttributeLists.Count > 0)
                {
                    CandidateEnums.Add(enumDecl);
                }
            }
        }
    }
}
